In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

In [4]:
#Filtro por objeto a los clientes que en este caso es el IPN
filtro1 = df[df["NOMBRE_CLIENTE"] == "INSTITUTO POLITECNICO NACIONAL"]
filtro1

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
92,F39637,2022-11-25,LETICIA RAMIREZ HERNANDEZ,INSTITUTO POLITECNICO NACIONAL,2,BB00103,BB INOX 34MMØX40MM 100W 127V STD C/TJ,728.43,0.00,168.53,1456.86,337.07,559.90,1119.79
390,F39053,2022-09-14,LETICIA RAMIREZ HERNANDEZ,INSTITUTO POLITECNICO NACIONAL,1,TUE00376,"TUB INOX 3/8""ØX66MMØ 250W 127V CIRCULAR",596.00,0.00,28.41,596.00,28.41,567.59,567.59
1143,F37553,2022-03-04,LETICIA RAMIREZ HERNANDEZ,INSTITUTO POLITECNICO NACIONAL,2,P7J6C1D1A030,"AEROPACK J 1/16""ØX2"" T-1/8""ØX11/2"" EXT1M",337.70,0.00,36.53,675.40,73.06,301.17,602.34
1242,F37403,2022-02-17,LETICIA RAMIREZ HERNANDEZ,INSTITUTO POLITECNICO NACIONAL,2,P7J6C1D1A030,"AEROPACK J 1/16""ØX2"" T-1/8""ØX11/2"" EXT1M",337.70,36.53,36.53,675.40,73.06,301.17,602.34
1367,F37138,2022-01-18,LETICIA RAMIREZ HERNANDEZ,INSTITUTO POLITECNICO NACIONAL,1,P7J6C1D1A030,"AEROPACK J 1/16""ØX2"" T-1/8""ØX11/2"" EXT1M",337.70,4.02,4.02,337.70,4.02,333.68,333.68

In [54]:
filtro1.to_csv("FILTRO1.csv")
#df=

In [ ]:
#Filtro por filas, iniciando de la posicion 24, y va de 100 en 100
filtro2= df.iloc[24::100,:]
filtro2

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
24,F39801,2022-12-21,LETICIA RAMIREZ HERNANDEZ,HOT MELT SISTEMAS Y SERVICIOS SANCHEZ,10,CS58R2200A01,"CAS 5/8""ØX14"" 240V 2000W EXT1MT",1357.50,0.00,405.55,13575.00,4055.46,951.95,9519.54
124,F39597,2022-11-17,LETICIA RAMIREZ HERNANDEZ,TIBASA UNIVERSAL FOREST PRODUCTS,1,TP0040,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 5 MT,462.00,153.85,153.85,462.00,153.85,308.15,308.15
224,F39390,2022-10-25,LETICIA RAMIREZ HERNANDEZ,JESUS BRYAN SEGURA SOLIS,8,BC00030,BC INOX 137MMØX100MM 1800W 240V BLOCK,2529.40,663.12,663.12,20235.20,5304.97,1866.28,14930.23
324,F39201,2022-09-30,ALFREDO CANELA,KERN LIEBERS MEXICO,4,EE00063,FABRICACIÓN ESPECIAL 1300W 115V,18869.00,0.00,1721.28,75476.00,6885.12,17147.72,68590.88
424,F39006,2022-09-08,LETICIA RAMIREZ HERNANDEZ,METAPLUS,3,BC00010,"BC PLANA 6""LARx4 1/4""ANC 2000W 220V C/TJ",2400.00,0.00,679.75,7200.00,2039.25,1720.25,5160.75
524,F38786,2022-08-10,ALFREDO CANELA,CEREALES Y PASTAS,4,70001691,CALTA 8MM Ø X 240 MM 500 W 220 V RECTO,413.40,91.50,91.50,1653.60,366.02,321.90,1287.58
624,F38580,2022-07-12,LETICIA RAMIREZ HERNANDEZ,INSTITUTO DEL DEPORTE Y LA RECREACION DEL ESTA...,1,TUA00459,"TUB INOX 7/16""ØX42CM 2000W 240V ""M"" BUSH",1165.95,345.97,345.97,1165.95,345.97,819.98,819.98
724,F38401,2022-06-17,ALFREDO CANELA,AVERY DENNISON,2,CAS00071,"CAS INOX 3/4""ØX260CM 2000W260V EXT.12""FV",800.19,67.69,67.69,1600.38,135.37,732.50,1465.01
824,F38196,2022-05-19,AARON NUÑO CORDOVA,HUMARCER DE QUERETARO,2,PT00084,PT-100 6MMØX110MM EXT15MTS TEFLON/ZAP,1548.00,0.00,599.82,3096.00,1199.64,948.18,1896.36
924,F37964,2022-04-25,LETICIA RAMIREZ HERNANDEZ,MANUFACTURAS METALICAS,10,TUS00003,"TUB. INOX. 5/16 Øx615mm. 2000W 440V ""U""""",695.20,46.14,46.14,6952.00,461.36,649.06,6490.64
1024,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.20,20448.01,958.52,57511.19
1124,F37602,2022-03-10,LETICIA RAMIREZ HERNANDEZ,DESECHOS INDUSTRIALES CONIN,1,TP0005,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 3 MT,375.29,87.10,87.10,375.29,87.10,288.19,288.19
1224,F37437,2022-02-22,LETICIA RAMIREZ HERNANDEZ,CROPLASTIC,1,BB1 1/2X1/2-300W,"BOQUILLA 11/2X1""1/2"" 300W 240V""",385.00,220.00,220.00,385.00,220.00,165.00,165.00
1324,F37231,2022-01-31,ALFREDO CANELA,DEACERO,2,93980461,"TERMOPAR K DOBLE CAL8 x18 FUND INOX 316""",2068.50,1298.68,1298.68,4137.00,2597.36,769.82,1539.64
1424,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56

In [55]:
filtro2.to_csv("FILTRO2.csv")
#df=

In [8]:
#Filtro por columnas a los datos de: nombre cliente y CANT
#filtro3=df.iloc[ : , 2:5]
filtro3= df.iloc[ : , 2:5]
filtro3

                NOMBRE_VENDEDOR                       NOMBRE_CLIENTE  CANT
0            AARON NUÑO CORDOVA                      TRILOGIQ-MEXICO     2
1     LETICIA RAMIREZ HERNANDEZ           JUAN GERARDO GUZMAN FLORES     3
2     LETICIA RAMIREZ HERNANDEZ                               TORJJS     3
3            AARON NUÑO CORDOVA                       CPEG SOLUTIONS     5
4            AARON NUÑO CORDOVA                      TRILOGIQ-MEXICO     2
...                         ...                                  ...   ...
1421   DIEGO ARMANDO LEON DURAN                   FIDEICOMISO F/1596     1
1422   DIEGO ARMANDO LEON DURAN                   FIDEICOMISO F/1596     1
1423   DIEGO ARMANDO LEON DURAN                      INDUSTRIAS NIBA     1
1424   DIEGO ARMANDO LEON DURAN            ANA BARBARA CRUZ PALACIOS     7
1425   DIEGO ARMANDO LEON DURAN  AIRBUS HELICOPTERS MEXICO QUERETARO     1

[1426 rows x 3 columns]

In [58]:
filtro3.to_csv("FILTRO3.csv")
#df=

In [17]:
df1= pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=2)
df1

,CVE_DOC,FECHA_DOC,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
NOMBRE_VENDEDOR,,,,,,,,,,,,,
AARON NUÑO CORDOVA,F39833,2022-12-23,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
LETICIA RAMIREZ HERNANDEZ,F39828,2022-12-23,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
LETICIA RAMIREZ HERNANDEZ,F39830,2022-12-23,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
AARON NUÑO CORDOVA,F39826,2022-12-23,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
AARON NUÑO CORDOVA,F39833,2022-12-23,TRILOGIQ-MEXICO,2,BN00145,BAN INOX 146MMØX40MM 500W230V CINT/ALLEN,1910.50,286.13,286.13,3821.00,572.25,1624.37,3248.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
DIEGO ARMANDO LEON DURAN,F37051,2022-01-05,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
DIEGO ARMANDO LEON DURAN,F37052,2022-01-05,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
DIEGO ARMANDO LEON DURAN,F37054,2022-01-05,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
DIEGO ARMANDO LEON DURAN,F37041,2022-01-05,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
DIEGO ARMANDO LEON DURAN,F37044,2022-01-05,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24

In [18]:
#Aplicamos filtro de filas vs columnas. Donde muestro la cantidad de ventas de Aaron
filtro4=df1.loc[["AARON NUÑO CORDOVA"], ["CANT"]]
filtro4

                    CANT
NOMBRE_VENDEDOR
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     5
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA    10
AARON NUÑO CORDOVA     2
...                  ...
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA     2
AARON NUÑO CORDOVA    20
AARON NUÑO CORDOVA     8
AARON NUÑO CORDOVA     2

[72 rows x 1 columns]

In [59]:
filtro4.to_csv("FILTRO4.csv")
#df=

In [ ]:
#Filtro por cabecera se filtran los primeros 5 datos, iniciando desde el 0
filtro5=df.head()
filtro5

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
1,F39828,2022-12-23,LETICIA RAMIREZ HERNANDEZ,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
2,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
3,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
4,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00145,BAN INOX 146MMØX40MM 500W230V CINT/ALLEN,1910.50,286.13,286.13,3821.00,572.25,1624.37,3248.75

In [60]:
filtro5.to_csv("FILTRO5.csv")
#df=

In [20]:
#Filtro por cola se muestrran los ultimos 5 datos de toda la base.
filtro6=df.tail()
filtro6

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1421,F37051,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1422,F37052,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1423,F37054,2022-01-05,DIEGO ARMANDO LEON DURAN,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
1424,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
1425,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24

In [61]:
filtro6.to_csv("FILTRO6.csv")
#df=

In [27]:
#filtro por comparacion comparo a que CANT sea mayor a 30 
filtro7=df[df["CANT"] > 30]
filtro7

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
631,F38583,2022-07-12,ALFREDO CANELA,TE.MEX AUTOMOTIVE,54,CAS00083,CAS INOX 12.5MMØX125MM 300W 280V EXT1MT,607.10,0.00,131.45,32783.62,7098.51,475.65,25685.11
681,F38484,2022-06-29,ALFREDO CANELA,CHAMPIÑONES SAN MIGUEL,100,BOBINA002,BOBINA DSD CAL.17 12mmØx410mm 4000W 254V,369.50,18.14,18.14,36950.00,1813.59,351.36,35136.41
772,F38312,2022-06-03,ALFREDO CANELA,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,266.04,266.04,52200.00,9577.26,1183.97,42622.74
810,F38221,2022-05-24,LETICIA RAMIREZ HERNANDEZ,TERMOFORMATEC,60,CAS00080,CAS INOX 18.5MMØX205MM 950W 440V EXT30CM,1296.00,0.00,244.07,77760.00,14643.92,1051.93,63116.08
901,F38047,2022-04-29,ALFREDO CANELA,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,35,ECQ-00972,"TUB. ENCAPSULADA 5/16Øx780mm 1500W 240V""",1475.30,335.51,335.51,51635.50,11742.95,1139.79,39892.55
1024,F37777,2022-03-31,ALFREDO CANELA,CLAVOS NACIONALES C.N,60,BOBINA001,BOBINA CAL.8 DSD C/TERMINALES EN INOX,1299.32,340.80,340.80,77959.20,20448.01,958.52,57511.19
1221,F37443,2022-02-23,DIEGO ARMANDO LEON DURAN,NHK SPRING MEXICO,36,TUE00146,TUB ESP 10MMØX1985MM 1000W 440V BUS/SOPO,1450.00,0.00,254.34,52200.00,9156.17,1195.66,43043.83
1385,F37098,2022-01-12,DIEGO ARMANDO LEON DURAN,REDYPLAST,40,CBS00045,"CART INOX 3/8""Øx8"" 340W, 220V CABLE 35CM",259.60,64.85,64.85,10384.00,2594.17,194.75,7789.83

In [62]:
filtro7.to_csv("FILTRO7.csv")
#df=

In [29]:
#Filtro Y, muestro que CANT sea menor que 30 Y que sea en la fecha 2022-03-14
filtro8 = df[(df["CANT"] < 30) & (df["FECHA_DOC"] == pd.Timestamp("2022-03-14"))]
filtro8

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
1115,F37620,2022-03-14,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,10,CAS00075,"CAS INOX 1/2""ØX51.5CM 400W240V EXT1M SOG",839.28,261.77,261.77,8392.8,2617.65,577.51,5775.15
1116,F37620,2022-03-14,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,15,CAS00076,"CAS INOX 5/8""ØX72CM 2670W 480V EXT.30CM",1078.50,0.00,351.08,16177.5,5266.17,727.42,10911.33

In [63]:
filtro8.to_csv("FILTRO8.csv")
#df=

In [ ]:
#Filtro O, muestro que CANT sea menor que 30 O que sea en la fecha 2022-12-23
filtro9 = df[(df["CANT"] < 30) | (df["FECHA_DOC"] == pd.Timestamp("2022-12-23"))]
filtro9

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BL00002,BL INOX 60mmØx50mm 400W 120/240V EXT30CM,925.82,65.31,65.31,1851.64,130.63,860.51,1721.01
1,F39828,2022-12-23,LETICIA RAMIREZ HERNANDEZ,JUAN GERARDO GUZMAN FLORES,3,TP00018,"TIRA INOX 38MMX6"" 150W 127V T/TIPO H",510.00,51.16,51.16,1530.00,153.49,458.84,1376.51
2,F39830,2022-12-23,LETICIA RAMIREZ HERNANDEZ,TORJJS,3,PJ31Q1G1A400,"TER J 3/16""ØX1/2"" EXT3MT MALLA INOX Z/E",439.15,0.00,123.21,1317.45,369.62,315.94,947.83
3,F39826,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,5,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1897.27,78.09,78.09,9486.35,390.43,1819.18,9095.92
4,F39833,2022-12-23,AARON NUÑO CORDOVA,TRILOGIQ-MEXICO,2,BN00145,BAN INOX 146MMØX40MM 500W230V CINT/ALLEN,1910.50,286.13,286.13,3821.00,572.25,1624.37,3248.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F37051,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1422,F37052,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1423,F37054,2022-01-05,DIEGO ARMANDO LEON DURAN,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
1424,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
1425,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24

In [76]:
filtro9.to_csv("FILTRO9.csv")
#df=

In [68]:
#Filtro not. Hago que NO se muestren los datos con la fecha 2022-12-23
filtro10 = df[~(df["FECHA_DOC"] == pd.Timestamp("2022-12-23"))]
filtro10

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
14,F39815,2022-12-22,ALFREDO CANELA,START SERVICE,1,RP00231,REPARACION DE MAQUINA,2300.00,0.00,99.68,2300.00,99.68,2200.32,2200.32
15,F39820,2022-12-22,AARON NUÑO CORDOVA,ABASTECIMIENTOS Y SERVICIOS ELECTRONICOS PROFE...,1,TU5/16X230MM,"TUBULAR J"" 5/16"" 230MM 4500W 220V""",1000.00,226.23,226.23,1000.00,226.23,773.77,773.77
16,F39817,2022-12-22,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,TP0016,"TERMOPAR CERAMICO T/K"" LONG 24"" CAL 8""",732.00,0.00,317.50,1464.00,635.00,414.50,829.00
17,F39812,2022-12-22,ALFREDO CANELA,CEREALES Y PASTAS,10,70001698,CARTUCHO ESC.Ø 8MM X 325 MM 500W 220V,488.00,107.33,107.33,4880.00,1073.25,380.67,3806.75
18,F39815,2022-12-22,ALFREDO CANELA,START SERVICE,1,RP00230,REPARACION DE PLANCHA DE CARTUCHOS 220V,5668.99,0.00,1319.88,5668.99,1319.88,4349.11,4349.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F37051,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1422,F37052,2022-01-05,DIEGO ARMANDO LEON DURAN,FIDEICOMISO F/1596,1,TUE00207,"TUB INCOLOY 1/2""Øx412mm J 9KW 240V PLACA",1615.00,0.00,586.32,1615.00,586.32,1028.68,1028.68
1423,F37054,2022-01-05,DIEGO ARMANDO LEON DURAN,INDUSTRIAS NIBA,1,BC00023,BC INOX 114MMØX165MM 1500W 230V C/ALLEN,2095.25,0.00,742.05,2095.25,742.05,1353.20,1353.20
1424,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
1425,F37044,2022-01-05,DIEGO ARMANDO LEON DURAN,AIRBUS HELICOPTERS MEXICO QUERETARO,1,RP00165,REPARACION DE BATIDOR 16.6KW 440V,14000.00,5323.76,5323.76,14000.00,5323.76,8676.24,8676.24

In [69]:
filtro10.to_csv("FILTRO10.csv")
#df=